version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    ports:
      - '8085:80'
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads   # Mount your local directory into the container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8087:80'
    environment:
      PMA_HOST: mysql  # MySQL service name (must match your MySQL service name)
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword  # MySQL root password
    depends_on:
      - mysql

volumes:
  mysql_data:
